### ISSUE TITLE
Can't find secret when not in the namespace of typesense

### ISSUE THREAD

**Issue by JoeTheDragon** [sai3010/Typesense-Kubernetes-Operator#33]
**Describe the bug**
Can't find secret when not in the namespace of typesense

│ HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"typesense-apikey\" not found","reason":"NotFound","details":{"name": │

**To Reproduce**
Install operator
create secret in target namespace
load typesense-cluster-values into target namespace

**Expected behavior**
Typesense to start up in target namespace

**Please complete the following information:**
 - Kubernetes version  v1.32.1 (microk8s) and v0.32.5 (GKE)
 - Typesense version  typesense-operator:3.0.1 typesense:27.1
 - GKE and microk8s

**Comment by numa1985** [comment]
@sai3010  : I am getting the similar issue that secret is not getting created in the "typesense" namespace. 

![Image](https://github.com/user-attachments/assets/9c6e3754-70d6-46aa-ab18-d07c81755f0b)

**Comment by sai3010** [comment]
Before launching the Typesense, the operator requires the secrets to be created in the same namespace as that of the operator itself as it takes care of injecting this secret to the Typesense pods. Please refer to the document for the commands.

**Comment by numa1985** [comment]
@sai3010 : Thanks for quick response. Created the secret as mentioned in the document and deployed the "Typesense operator" in the same namespace as the secret ,still landing up with the same error .

ubuntu@NARU-Pr5530:~/28022025$ kubectl get secret -n type-sense
NAME               TYPE     DATA   AGE
typesense-apikey   Opaque   1      7m56s
ubuntu@NARU-Pr5530:~/28022025$

![Image](https://github.com/user-attachments/assets/bc5663cd-0a43-4ba3-9fce-97ef874fd907)

**Comment by sai3010** [comment]
Hey @numa1985 , Could you schedule a call so that i can help you trouble shoot this ? 
Please find the link here: https://topmate.io/saiprasanth/1461896

**Comment by sai3010** [comment]
Hey @numa1985 
I'm closing this thread due to inactivity. Please feel free to re-open.

**Comment by sai3010** [comment]
Hey @numa1985 ,
I have fixed this issue in the latest release. Please do check.

**Comment by allsilaevex** [comment]
@sai3010 hi! I'm using `sai3010/typesense-operator:3.1` and still get the error:
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/handler.py", line 49, in update_fn
    spec = validate_spec(kwargs, k8s_core_v1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deployment_utils.py", line 56, in validate_spec
    secret = k8s_core_v1.read_namespaced_secret(name=secret_name,namespace=operator_namespace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 25013, in read_namespaced_secret
    return self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 25073, in read_namespaced_secret_with_http_info
    raise ApiValueError("Missing the required parameter `namespace` when calling `read_namespaced_secret`")  # noqa: E501
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubernetes.client.exceptions.ApiValueError: Missing the required parameter `namespace` when calling `read_namespaced_secret`
```
I already have a secret `typesense/typesense-apikey` created and the namespace is specified:
```yaml
apiVersion: typesenseproject.org/v1
kind: TypesenseOperator
metadata:
  name: type-operator
  namespace: typesense
spec:
  replicas: 1
  namespace: typesense
  image: typesense/typesense:28.0
  env:
  - name: APIKEY
    valueFrom:
      secretKeyRef:
        key: apikey
        name: typesense-apikey
        namespace: typesense
  nodeSelector:
    kubernetes.io/hostname: node1
config:
  secret: "typesense-apikey"
  env:
    TYPESENSE_ENABLE_CORS: "true"
```

**Comment by sai3010** [comment]
Hey
Could you clarify the following?
- what is the namespace of typesense-apikey secret? is it in the same namespace as the operator pod?
- this error is happening while creating operator i.e kubectl create or kubectl apply?

**Comment by sai3010** [comment]
Also @allsilaevex , I have released a patch fix 3.1.1 that may solve your issue. Please do try it out.

**Comment by allsilaevex** [comment]
@sai3010 you're great! it helped and now everything works, thanks a lot!

**Comment by sai3010** [comment]
@allsilaevex Please do consider joining our community!
